### ISSUE TITLE
don't work with spring fat jar

### ISSUE THREAD

**Issue by sdhjl2000** [electronicarts/ea-agent-loader#7]
https://github.com/spring-projects/spring-boot/issues/4868
Agent class inside fat jar loaded by LaunchedURLClassLoader  invisible  to SysClassLoader,fire ClassNotFoundException  when call sun.instrument.InstrumentationImpl.loadClassAndCallAgentmain

**Comment by JoeHegarty** [comment]
This project is now deprecated and archived.
