### ISSUE TITLE
Can I unload javaagent in the runtime?

### ISSUE THREAD

**Issue by gluckzhang** [electronicarts/ea-agent-loader#8]
Hi! This agent-loader is wonderful, I use it a lot to test my javaagent.
However, my agent needs to input some params, when I run different test cases, the params might be different. Is there any method to unload / reload the agent? So that I can design my testcases more conveniently.
Thanks!

**Comment by DanielSperry** [comment]
If you just need to load the agent multiple times this sample test case shows that it can be done:

[AgentLoaderTest.java](https://github.com/electronicarts/ea-agent-loader/blob/master/agent-loader/src/test/java/com/ea/agentloader/test/AgentLoaderTest.java)

The agentmain will be called again with different `agentArgs`.

AFAIK you won't be able to actually unload the agent, but you might be able to write it's code as to reinitialize it once agentmain gets called a second time.

**Comment by gluckzhang** [comment]
Hi Daniel, thank you for your prompt reply!
I do find that when I use `AgentLoader.loadAgentClass` again, it can call agentmain again with new args. Maybe I have to dig into the agent codes, to realize the reinitialization:)

**Comment by DanielSperry** [comment]
One thing you could do if you want the agent to be installed twice is to wrap it with another class before each test. You can do that manually as bellow or, if you have a lot of tests, generate some bytecode and do it automatically.

Manually it would look like this:

    public static class AgentForT1 {
        public static void agentmain(String agentArgs, Instrumentation inst)  {
            YourAgent.agentmain(agentArgs, inst);
        }
    }

    @Test
    public void test1() {
        // ...
        AgentLoader.loadAgentClass(AgentForT1.class.getName(), options, null, false, false, false);
    }
    @Test
    public void test2()  {
        AgentLoader.loadAgentClass(AgentForT2.class.getName(), options, null, false, false, false);
    }

**Comment by gluckzhang** [comment]
Excellent, thanks for your help!
