### ISSUE TITLE
Does not work with aspectjweaver

### ISSUE THREAD

**Issue by dpalic** [electronicarts/ea-agent-loader#9]
Do I have to handle somehow specially AspectJ?
I tried to execute as first call in the main method, without any success:

`      AgentLoader.loadAgentClass(Agent.class.getName(), null);

where Agent.class is "import org.aspectj.weaver.loadtime.Agent";

My aspect is only getting executed after I add to jvm start:

`-javaagent:${env_var:HOME}/.m2/repository/org/aspectj/aspectjweaver/1.8.13/aspectjweaver-1.8.13.jar`

Any advice or even better a solution?

**Comment by JoeHegarty** [comment]
As far as I am aware this should work fine. What JDK are you using?

**Comment by JoeHegarty** [comment]
This project is now deprecated and archived.
